name: ecoli-variant-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastqc=0.12.1
  - trimmomatic=0.39
  - bwa=0.7.17
  - samtools=1.17
  - bcftools=1.17
  - python=3.10
